# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85c741ed37fd580ffc091a309d2458fce67fbd906a169c0f9f6f7e1033c81b8cd49345413b284a6f887af6891abf258407c6d9a2ddd423ed6a1e9b4592e546df

test:
  secret_key_base: f6540eac9751438a0a89b41208d64820f9f9e2e3b6603026c9dc795944861e386cef45e8eaeff7c5e18d73112d6a831e980f9fcbb329b1f38ea582eb097cd984

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
